"""Closed, asset-addressed Camera Coach training augmentations.

This module deliberately does not manufacture a canonical derived record.
The source record remains immutable and dataset-owned.  A training result is
accepted only when a trusted schedule, an M3-008 authority generated from the
same complete source bundle, and a replay of the actual encoded assets agree.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
import hashlib
import json
import math
from io import BytesIO
from pathlib import Path
import re
import struct
from tempfile import TemporaryDirectory
from typing import Any, Mapping, Sequence

from PIL import Image

from tools import camera_dataset_audit as _m3
from tools.dataset.camera_coach_check import ACTION_IDS, VERIFIER_IDS, validate_record


ROOT = Path(__file__).resolve().parents[3]
CAMERA_DIR = ROOT / "datasets" / "camera-coach" / "v1"
LABEL_SCHEMA_PATH = CAMERA_DIR / "label-schema.json"
CONTRACT_PATH = ROOT / "ml" / "camera_coach" / "contracts" / "set_composition_net_v1.json"
CLUSTER_SCHEMA_PATH = CAMERA_DIR / "cluster-schema.json"
SPLIT_SCHEMA_PATH = CAMERA_DIR / "split-manifest-schema.json"
DERIVATION_MANIFEST_PATH = CAMERA_DIR / "derivation-manifest.jsonl"

RECORD_SCHEMA_VERSION = "v1.0.0"
AUGMENTATION_VERSION = "v3.0.0"
POLICY_SCHEMA_ID = "camera-augmentation-policy-v3"
LINEAGE_SCHEMA_ID = "camera-augmentation-lineage-v3"
SCHEDULE_SCHEMA_ID = "camera-augmentation-schedule-v1"
SCHEDULE_SCHEMA_VERSION = "v1.0.0"
ID_RE = re.compile(r"^[a-z0-9][a-z0-9._-]*$")
SHA256_RE = re.compile(r"^[0-9a-f]{64}$")

# The repository's only byte-level fixture authority.  These are hashes of
# deterministic synthetic PNGs generated by the focused checker, never real
# media.  Grouped production records have no per-asset digest in the frozen v1
# schema and therefore fail closed unless an external M3 authority is added.
_FIXTURE_ASSET_SHA256 = {
    "asset-still-fixture-001": "96b3febf39c4e35f2f3ff5d008a46f9e8774c48331d7925b096f120fedf4556a",
    "asset-seq-fixture-002-f0": "d8bf62ec82ab5ee160458eb2f5a6e7a6507c6ec97579bcba62c929685c66583a",
    "asset-seq-fixture-002-f1": "4f174d180b6a628b308d9ddc8607863ee5c676ec9ef22cf72745de1034580696",
    "asset-seq-fixture-002-f2": "fc50e46d7e27328f9b4d20eb1545e67ebe972c2df03c9566d5631e4f1e3b8298",
    "asset-episode-fixture-003-before": "76dd8e1f052e8d556a38616ea90ba8636133c8e1b6f45ea9f51191d69c4cc6d3",
    "asset-episode-fixture-003-after": "49506a05e22e2cb69928636c629f5e09ba00f234a17b1f586c03227ab3c01543",
}


class AugmentationError(ValueError):
    """Raised when an augmentation input crosses the closed trust boundary."""

# The only directional IDs admitted by this owner are the explicit frozen
# pairs below.  The canonical v1 validator rejects every other unknown ID.
ACTION_PAIRS = (
    ("shift_frame_left", "shift_frame_right"),
    ("move_subject_left", "move_subject_right"),
    ("move_object_left", "move_object_right"),
)
VERIFIER_PAIRS = (
    ("framing_left_improves", "framing_right_improves"),
    ("subject_position_improves_left", "subject_position_improves_right"),
    ("object_position_improves_left", "object_position_improves_right"),
)
PROTECTED_CATEGORIES = tuple(_m3.PROTECTED_CATEGORIES)

_ACTION_PAIR_NAMES = {item for pair in ACTION_PAIRS for item in pair}
_VERIFIER_PAIR_NAMES = {item for pair in VERIFIER_PAIRS for item in pair}
if any(item not in ACTION_IDS for item in _ACTION_PAIR_NAMES) or any(item not in VERIFIER_IDS for item in _VERIFIER_PAIR_NAMES):
    raise AugmentationError("remap authority references an unfrozen action or verifier")
if any(("left" in item or "right" in item) and item not in _ACTION_PAIR_NAMES for item in ACTION_IDS):
    raise AugmentationError("frozen directional action is not explicitly remapped")
if any(("left" in item or "right" in item) and item not in _VERIFIER_PAIR_NAMES for item in VERIFIER_IDS):
    raise AugmentationError("frozen directional verifier is not explicitly remapped")

_REMAP_AUTHORITY = {
    "action_pairs": [list(pair) for pair in ACTION_PAIRS],
    "verifier_pairs": [list(pair) for pair in VERIFIER_PAIRS],
    "locations": [
        "label.acceptable_action_ids",
        "label.forbidden_action_ids",
        "label.selected_action_id",
        "label.issues[*].acceptable_action_ids",
        "label.issues[*].forbidden_action_ids",
        "label.verification[*].action_id",
        "label.verification[*].verifier_id",
        "episode.action_step.action_id",
        "episode.outcome_verifier",
        "subject.candidates[*].region",
    ],
}
_SCHEDULE_AUTHORITY = {
    "schema_id": SCHEDULE_SCHEMA_ID,
    "schema_version": SCHEDULE_SCHEMA_VERSION,
    "job_keys": ["job_id", "record_id", "kind", "parameters", "seed", "sample_counter"],
    "kinds": ["horizontal_flip", "photometric_identity", "photometric", "crop"],
    "supported_kinds": ["horizontal_flip", "photometric_identity"],
    "blocked_kinds": ["photometric", "crop"],
    "parameters": {
        "horizontal_flip": [],
        "photometric_identity": [],
        "photometric": [],
        "crop": [],
    },
}
REMAP_AUTHORITY_SHA256 = hashlib.sha256(json.dumps(_REMAP_AUTHORITY, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")).hexdigest()
SCHEDULE_AUTHORITY_SHA256 = hashlib.sha256(json.dumps(_SCHEDULE_AUTHORITY, sort_keys=True, separators=(",", ":"), ensure_ascii=False).encode("utf-8")).hexdigest()


def canonical_json(value: Any) -> str:
    try:
        return json.dumps(value, ensure_ascii=False, sort_keys=True, separators=(",", ":"), allow_nan=False)
    except (TypeError, ValueError, OverflowError, RecursionError) as exc:
        raise AugmentationError("value is not canonical JSON") from exc


def digest(value: Any) -> str:
    return hashlib.sha256(canonical_json(value).encode("utf-8")).hexdigest()


def _remap_authority() -> dict[str, Any]:
    return {
        "action_pairs": [list(pair) for pair in ACTION_PAIRS],
        "verifier_pairs": [list(pair) for pair in VERIFIER_PAIRS],
        "locations": list(_REMAP_AUTHORITY["locations"]),
    }


def _remap_authority_sha256() -> str:
    return digest(_remap_authority())


def _schedule_authority_sha256() -> str:
    return digest(_SCHEDULE_AUTHORITY)


def _file_digest(path: Path) -> str:
    try:
        return hashlib.sha256(path.read_bytes()).hexdigest()
    except OSError as exc:
        raise AugmentationError(f"authority file is unreadable: {path}") from exc


def _config() -> dict[str, Any]:
    return {
        "augmentation_version": AUGMENTATION_VERSION,
        "policy_schema_id": POLICY_SCHEMA_ID,
        "lineage_schema_id": LINEAGE_SCHEMA_ID,
        "schedule_schema_id": SCHEDULE_SCHEMA_ID,
        "schedule_schema_version": SCHEDULE_SCHEMA_VERSION,
        "label_schema_sha256": _file_digest(LABEL_SCHEMA_PATH),
        "contract_sha256": _file_digest(CONTRACT_PATH),
        "cluster_schema_sha256": _file_digest(CLUSTER_SCHEMA_PATH),
        "split_schema_sha256": _file_digest(SPLIT_SCHEMA_PATH),
        "remap_authority_sha256": _remap_authority_sha256(),
        "schedule_authority_sha256": _schedule_authority_sha256(),
        "fixture_asset_sha256": _FIXTURE_ASSET_SHA256,
        "pixel_codec": "encoded-image-decode-rgb8-v1",
        "source_asset_authority": "m3-008-cluster-receipt-v1",
        "eligible_split_owners": ["train", "calibration"],
    }


AUGMENTATION_CONFIG = _config()
AUGMENTATION_CONFIG_SHA256 = digest(AUGMENTATION_CONFIG)


def _id(value: Any, label: str) -> str:
    if type(value) is not str or ID_RE.fullmatch(value) is None:
        raise AugmentationError(f"invalid {label}")
    return value


def _sha(value: Any, label: str) -> str:
    if type(value) is not str or SHA256_RE.fullmatch(value) is None:
        raise AugmentationError(f"invalid {label}")
    return value


def _uint(value: Any, label: str) -> int:
    if type(value) is not int or value < 0 or value > 2**63 - 1:
        raise AugmentationError(f"invalid {label}")
    return value


def _finite(value: Any, label: str) -> float:
    if type(value) not in (int, float) or isinstance(value, bool) or not math.isfinite(float(value)):
        raise AugmentationError(f"invalid {label}")
    return float(value)


def _record(record: Any) -> dict[str, Any]:
    if type(record) is not dict:
        raise AugmentationError("source record must be a plain object")
    errors = validate_record(record, {}, admission=False)
    if errors:
        raise AugmentationError(f"source record is not canonical-valid: {errors[0]}")
    return copy.deepcopy(record)


def _required_asset_ids(record: Mapping[str, Any]) -> tuple[str, ...]:
    media = record["media"]
    asset_ids = media["asset_ids"]
    if type(asset_ids) is not list or not asset_ids:
        raise AugmentationError("source media.asset_ids must be non-empty")
    ids = tuple(_id(item, "media.asset_ids item") for item in asset_ids)
    if len(set(ids)) != len(ids):
        raise AugmentationError("duplicate source media asset")
    if record["record_type"] == "still" and (len(ids) != 1 or media["asset_id"] != ids[0]):
        raise AugmentationError("still media.asset_id must identify its sole asset")
    if record["record_type"] == "temporal":
        sequence = record.get("sequence")
        if type(sequence) is not dict or set(frame["asset_id"] for frame in sequence["frames"]) != set(ids):
            raise AugmentationError("temporal frame/media asset mismatch")
    if record["record_type"] == "episode":
        episode = record.get("episode")
        if type(episode) is not dict:
            raise AugmentationError("episode media asset mapping is missing")
        episode_ids = {episode["before"]["asset_id"], episode["after"]["asset_id"]}
        if episode_ids != set(ids):
            raise AugmentationError("episode before/after media asset mismatch")
    return tuple(sorted(ids))


def _decode(encoded: bytes, asset_id: str) -> tuple[int, int, bytes]:
    if type(encoded) is not bytes or not encoded:
        raise AugmentationError(f"asset {asset_id} must contain encoded bytes")
    try:
        with Image.open(BytesIO(encoded)) as opened:
            opened.verify()
        with Image.open(BytesIO(encoded)) as opened:
            if getattr(opened, "n_frames", 1) != 1:
                raise AugmentationError(f"asset {asset_id} must be one frame")
            opened.load()
            if opened.width < 1 or opened.height < 1:
                raise AugmentationError(f"asset {asset_id} has invalid dimensions")
            image = opened.convert("RGB")
            return image.height, image.width, image.tobytes()
    except AugmentationError:
        raise
    except (OSError, ValueError) as exc:
        raise AugmentationError(f"asset {asset_id} is not a deterministic RGB image") from exc


def _asset_pixels_digest(assets: Sequence["_DecodedAsset"]) -> str:
    body = bytearray(b"camera-pixel-bundle-v1\0")
    for asset in assets:
        encoded_id = asset.asset_id.encode("utf-8")
        body.extend(struct.pack(">I", len(encoded_id)))
        body.extend(encoded_id)
        body.extend(struct.pack(">II", asset.height, asset.width))
        body.extend(asset.pixels)
    return hashlib.sha256(bytes(body)).hexdigest()


def _pixels_to_bytes(pixels: Any, label: str) -> tuple[int, int, bytes]:
    if type(pixels) is not list or not pixels or any(type(row) is not list for row in pixels):
        raise AugmentationError(f"{label} must be a non-empty HWC list")
    width = len(pixels[0])
    if width < 1 or any(len(row) != width for row in pixels):
        raise AugmentationError(f"{label} has inconsistent rows")
    packed = bytearray()
    for row in pixels:
        for pixel in row:
            if type(pixel) is not list or len(pixel) != 3:
                raise AugmentationError(f"{label} must contain RGB triples")
            for channel in pixel:
                if type(channel) is not int or isinstance(channel, bool) or not 0 <= channel <= 255:
                    raise AugmentationError(f"{label} contains an invalid channel")
                packed.append(channel)
    return len(pixels), width, bytes(packed)


def _bytes_to_pixels(height: int, width: int, pixels: bytes) -> list[list[list[int]]]:
    return [[list(pixels[(row * width + column) * 3 : (row * width + column + 1) * 3]) for column in range(width)] for row in range(height)]


@dataclass(frozen=True, slots=True)
class _DecodedAsset:
    asset_id: str
    encoded: bytes
    encoded_sha256: str
    height: int
    width: int
    pixels: bytes


class SourceBundle:
    """Immutable canonical record plus every concrete asset it addresses."""

    __slots__ = ("_record_json", "_assets")

    def __init__(self, record_json: str, assets: tuple[_DecodedAsset, ...], token: object) -> None:
        if token is not _SOURCE_TOKEN:
            raise TypeError("SourceBundle is produced by make_source_bundle")
        self._record_json = record_json
        self._assets = assets

    @property
    def record(self) -> dict[str, Any]:
        return copy.deepcopy(json.loads(self._record_json))

    @property
    def asset_ids(self) -> tuple[str, ...]:
        return tuple(item.asset_id for item in self._assets)

    def _decoded(self, asset_id: str) -> _DecodedAsset:
        for asset in self._assets:
            if asset.asset_id == asset_id:
                return asset
        raise AugmentationError(f"source asset is not present: {asset_id}")


_SOURCE_TOKEN = object()


def make_source_bundle(record: Mapping[str, Any], assets: Mapping[str, Any]) -> SourceBundle:
    """Validate a canonical record and bind all supplied bytes to its assets."""

    source = _record(record)
    expected_ids = _required_asset_ids(source)
    if type(assets) is not dict:
        raise AugmentationError("source assets must be an asset_id-to-bytes object")
    supplied_ids = tuple(sorted(_id(key, "asset map key") for key in assets))
    if supplied_ids != expected_ids:
        raise AugmentationError("source asset bundle is missing or has extra assets")
    decoded: list[_DecodedAsset] = []
    for asset_id in expected_ids:
        value = assets[asset_id]
        if type(value) is not bytes:
            raise AugmentationError("asset values must be encoded bytes")
        encoded = value
        height, width, pixels = _decode(encoded, asset_id)
        actual_sha = hashlib.sha256(encoded).hexdigest()
        decoded.append(_DecodedAsset(asset_id, encoded, actual_sha, height, width, pixels))
    fixture_only = source["provenance"]["source_kind"] == "synthetic_fixture" and source["provenance"]["rights_disposition"] == "fixture_only"
    if source["record_type"] == "still" and source["media"]["content_sha256"] != decoded[0].encoded_sha256:
        raise AugmentationError("record media.content_sha256 does not match actual asset bytes")
    if fixture_only:
        for asset in decoded:
            if _FIXTURE_ASSET_SHA256.get(asset.asset_id) != asset.encoded_sha256:
                raise AugmentationError(f"fixture asset bytes disagree with canonical fixture mapping: {asset.asset_id}")
    elif source["record_type"] != "still":
        raise AugmentationError("requires_external_asset_authority: grouped v1 media has no per-asset content digest")
    return SourceBundle(canonical_json(source), tuple(decoded), _SOURCE_TOKEN)


def _record_sequences(record: Mapping[str, Any]) -> tuple[str, ...]:
    if record["record_type"] == "temporal":
        return (_id(record["sequence"]["sequence_id"], "sequence_id"),)
    if record["record_type"] == "episode":
        # M3-008 requires a sequence owner for episode assets.  The frozen
        # episode_id is the explicit before/after grouping identity.
        return (_id(record["episode"]["episode_id"], "episode_id"),)
    return ()


def _asset_metadata(record: Mapping[str, Any], asset_id: str) -> tuple[tuple[str, ...], tuple[int, ...]]:
    if record["record_type"] == "temporal":
        for frame in record["sequence"]["frames"]:
            if frame["asset_id"] == asset_id:
                return (record["sequence"]["sequence_id"],), (frame["ordinal"],)
    if record["record_type"] == "episode":
        before = record["episode"]["before"]["asset_id"]
        return (record["episode"]["episode_id"],), (0 if asset_id == before else 1,)
    return (), ()


def _bundle_list(bundles: Any) -> list[SourceBundle]:
    if type(bundles) is not list or not bundles:
        raise AugmentationError("source bundle collection must be a non-empty list")
    if any(type(bundle) is not SourceBundle for bundle in bundles):
        raise AugmentationError("source bundle collection contains an invalid object")
    record_ids = [bundle.record["record_id"] for bundle in bundles]
    if len(set(record_ids)) != len(record_ids):
        raise AugmentationError("duplicate source record in bundle collection")
    return bundles


class ClusterAuthority:
    __slots__ = ("_receipt_json", "_asset_hashes", "_asset_clusters", "_sha256")

    def __init__(self, receipt: dict[str, Any], token: object) -> None:
        if token is not _AUTHORITY_TOKEN:
            raise TypeError("ClusterAuthority is produced by make_cluster_authority")
        self._receipt_json = canonical_json(receipt)
        self._asset_hashes = _cluster_asset_hashes(receipt)
        self._asset_clusters = {asset_id: data["cluster_id"] for asset_id, data in self._asset_hashes.items()}
        self._sha256 = digest(receipt)

    @property
    def receipt_sha256(self) -> str:
        return self._sha256

    @property
    def asset_ids(self) -> tuple[str, ...]:
        return tuple(sorted(self._asset_hashes))

    def receipt(self) -> dict[str, Any]:
        return copy.deepcopy(json.loads(self._receipt_json))

    def asset_sha256(self, asset_id: str) -> str:
        try:
            return self._asset_hashes[asset_id]["content_sha256"]
        except KeyError as exc:
            raise AugmentationError(f"asset is absent from M3 cluster authority: {asset_id}") from exc

    def cluster_id(self, asset_id: str) -> str:
        try:
            return self._asset_clusters[asset_id]
        except KeyError as exc:
            raise AugmentationError(f"asset is absent from M3 cluster authority: {asset_id}") from exc


class SplitAuthority:
    __slots__ = ("_receipt_json", "_assignments", "_seed", "_ratios", "_cluster", "_sha256")

    def __init__(self, receipt: dict[str, Any], cluster: ClusterAuthority, token: object) -> None:
        if token is not _AUTHORITY_TOKEN:
            raise TypeError("SplitAuthority is produced by make_split_authority")
        self._receipt_json = canonical_json(receipt)
        self._assignments = {row["record_id"]: row["split"] for row in receipt["assignments"]}
        self._seed = receipt["config"]["seed"]
        self._ratios = tuple((name, receipt["config"]["ratios"][name]) for name in _m3.SPLITS)
        self._cluster = cluster
        self._sha256 = receipt["manifest_sha256"]

    @property
    def manifest_sha256(self) -> str:
        return self._sha256

    @property
    def record_ids(self) -> tuple[str, ...]:
        return tuple(sorted(self._assignments))

    @property
    def seed(self) -> int:
        return self._seed

    @property
    def ratios(self) -> dict[str, float]:
        return dict(self._ratios)

    @property
    def cluster(self) -> ClusterAuthority:
        return self._cluster

    def receipt(self) -> dict[str, Any]:
        return copy.deepcopy(json.loads(self._receipt_json))

    def split(self, record_id: str) -> str:
        try:
            return self._assignments[record_id]
        except KeyError as exc:
            raise AugmentationError(f"record is absent from M3 split authority: {record_id}") from exc


_AUTHORITY_TOKEN = object()


def _cluster_asset_hashes(receipt: Mapping[str, Any]) -> dict[str, dict[str, str]]:
    try:
        _m3.validate_cluster_output(dict(receipt))
    except Exception as exc:
        raise AugmentationError(f"invalid M3 cluster authority: {exc}") from exc
    result: dict[str, dict[str, str]] = {}
    for cluster in receipt["clusters"]:
        for member in cluster["members"]:
            asset_id = _id(member["asset_id"], "cluster asset_id")
            if asset_id in result:
                raise AugmentationError(f"duplicate M3 asset authority: {asset_id}")
            result[asset_id] = {
                "content_sha256": _sha(member["content_sha256"], "cluster content_sha256"),
                "cluster_id": cluster["cluster_id"],
            }
    if not result:
        raise AugmentationError("M3 cluster authority has no assets")
    return result


def _m3_items(bundles: list[SourceBundle], root: Path) -> list[_m3.MediaItem]:
    merged: dict[str, dict[str, Any]] = {}
    for bundle in bundles:
        record = bundle.record
        record_id = record["record_id"]
        for asset_id in bundle.asset_ids:
            decoded = bundle._decoded(asset_id)
            sequences, ordinals = _asset_metadata(record, asset_id)
            item = merged.setdefault(
                asset_id,
                {
                    "encoded": decoded.encoded,
                    "record_ids": set(),
                    "sequence_ids": set(),
                    "frame_ordinals": set(),
                    "derivation_family_ids": set(),
                },
            )
            if item["encoded"] != decoded.encoded:
                raise AugmentationError(f"asset bytes conflict across source records: {asset_id}")
            item["record_ids"].add(record_id)
            item["sequence_ids"].update(sequences)
            item["frame_ordinals"].update(ordinals)
            item["derivation_family_ids"].add(record["provenance"]["derivation_family_id"])
    items: list[_m3.MediaItem] = []
    for index, asset_id in enumerate(sorted(merged)):
        item = merged[asset_id]
        path = root / f"asset-{index}.bin"
        path.write_bytes(item["encoded"])
        items.append(
            _m3.MediaItem(
                asset_id=asset_id,
                path=path,
                record_ids=tuple(sorted(item["record_ids"])),
                sequence_ids=tuple(sorted(item["sequence_ids"])),
                frame_ordinals=tuple(sorted(item["frame_ordinals"])),
                derivation_family_ids=tuple(sorted(item["derivation_family_ids"])),
                declared_sha256=hashlib.sha256(item["encoded"]).hexdigest(),
            )
        )
    return items


def make_cluster_authority(bundles: list[SourceBundle]) -> ClusterAuthority:
    """Run the existing M3-008 owner over every supplied concrete asset."""

    checked = _bundle_list(bundles)
    with TemporaryDirectory(prefix="camera-augmentation-m3-") as temp:
        try:
            receipt = _m3.cluster_media(_m3_items(checked, Path(temp)))
        except Exception as exc:
            raise AugmentationError(f"M3 cluster authority generation failed: {exc}") from exc
    return ClusterAuthority(receipt, _AUTHORITY_TOKEN)


def _split_projection(record: Mapping[str, Any]) -> dict[str, Any]:
    provenance = record["provenance"]
    capture = record["capture"]
    projection: dict[str, Any] = {
        "record_id": record["record_id"],
        "record_type": record["record_type"],
        "bucket": "synthetic" if provenance["source_kind"] == "synthetic_fixture" else "organic",
        "rights_disposition": provenance["rights_disposition"],
        "source_shoot_id": provenance["source_shoot_id"],
        "scene_family_id": capture["scene_family_id"],
        "person_family_ids": list(capture["person_family_ids"]),
        "location_family_id": capture["location_family_id"],
        "time_family_id": capture["time_family_id"],
        "take_family_id": capture["take_family_id"],
        "device_family_id": capture["device_family_id"],
        "derivation_family_id": provenance["derivation_family_id"],
        "asset_ids": list(record["media"]["asset_ids"]),
        "review": copy.deepcopy(record["review"]),
    }
    sequence_ids = _record_sequences(record)
    if sequence_ids:
        projection["sequence_id"] = sequence_ids[0]
    if record["record_type"] == "temporal":
        projection["sequence"] = {
            "sequence_id": sequence_ids[0],
            "derivation_family_id": provenance["derivation_family_id"],
            "frames": [
                {
                    "asset_id": frame["asset_id"],
                    "sequence_id": sequence_ids[0],
                    "ordinal": frame["ordinal"],
                    "derivation_family_id": provenance["derivation_family_id"],
                }
                for frame in record["sequence"]["frames"]
            ],
        }
    return projection


def _m3_records(bundles: list[SourceBundle]) -> list[_m3.SplitRecord]:
    payload = {
        "manifest_type": _m3.SPLIT_MANIFEST_TYPE,
        "schema_id": _m3.SPLIT_INPUT_SCHEMA_ID,
        "schema_version": _m3.SCHEMA_VERSION,
        "entries": [],
    }
    payload["entries"] = [_split_projection(bundle.record) for bundle in bundles]
    with TemporaryDirectory(prefix="camera-augmentation-split-") as temp:
        path = Path(temp) / "split-input.json"
        path.write_text(canonical_json(payload), encoding="utf-8")
        try:
            return _m3.load_split_manifest(path)
        except Exception as exc:
            raise AugmentationError(f"M3 split input generation failed: {exc}") from exc


def make_split_authority(
    bundles: list[SourceBundle],
    cluster_authority: ClusterAuthority,
    *,
    seed: int = 0,
    train_ratio: float = 0.8,
    calibration_ratio: float = 0.1,
    locked_test_ratio: float = 0.1,
) -> SplitAuthority:
    """Recompute the M3-008 protected split from the complete source bundle."""

    checked = _bundle_list(bundles)
    if type(cluster_authority) is not ClusterAuthority:
        raise AugmentationError("cluster authority is required")
    actual_assets = tuple(sorted({asset_id for bundle in checked for asset_id in bundle.asset_ids}))
    if tuple(cluster_authority.asset_ids) != actual_assets:
        raise AugmentationError("cluster authority does not cover the complete source bundle")
    records = _m3_records(checked)
    try:
        receipt = _m3.split_records(
            records,
            cluster_authority.receipt(),
            seed=_uint(seed, "split seed"),
            train_ratio=_finite(train_ratio, "train ratio"),
            calibration_ratio=_finite(calibration_ratio, "calibration ratio"),
            locked_test_ratio=_finite(locked_test_ratio, "locked test ratio"),
        )
    except Exception as exc:
        raise AugmentationError(f"M3 split authority generation failed: {exc}") from exc
    return SplitAuthority(receipt, cluster_authority, _AUTHORITY_TOKEN)


def _normal_split(value: Any) -> str:
    if value == "holdout":
        return "locked_test"
    if value in _m3.SPLITS:
        return value
    raise AugmentationError("source record has no admissible split owner")


def _effective_split(record: Mapping[str, Any], split_authority: SplitAuthority) -> str:
    """Resolve fixture-only records without pretending fixture review is train review."""

    assigned = split_authority.split(record["record_id"])
    if record["split"] == "fixture":
        if record["provenance"]["source_kind"] != "synthetic_fixture" or record["provenance"]["rights_disposition"] != "fixture_only":
            raise AugmentationError("fixture split requires synthetic fixture-only provenance")
        return assigned
    if _normal_split(record["split"]) != assigned:
        raise AugmentationError(f"record split disagrees with M3 authority: {record['record_id']}")
    return assigned


def _protected_families(record: Mapping[str, Any], cluster: ClusterAuthority) -> dict[str, list[str]]:
    capture = record["capture"]
    provenance = record["provenance"]
    families = {
        "source_shoot": [provenance["source_shoot_id"]],
        "scene": [capture["scene_family_id"]],
        "person": sorted(capture["person_family_ids"]),
        "location": [capture["location_family_id"]],
        "time": [capture["time_family_id"]],
        "derivation": [provenance["derivation_family_id"]],
        "sequence": list(_record_sequences(record)),
        "take": [capture["take_family_id"]],
        "device": [capture["device_family_id"]],
        "dedup_cluster": sorted({cluster.cluster_id(asset_id) for asset_id in _required_asset_ids(record)}),
    }
    return {category: families[category] for category in PROTECTED_CATEGORIES}


def _validate_job(job: Any) -> dict[str, Any]:
    if type(job) is not dict:
        raise AugmentationError("schedule job must be a plain object")
    expected = {"job_id", "record_id", "kind", "parameters", "seed", "sample_counter"}
    if set(job) != expected:
        raise AugmentationError("schedule job has unknown or missing keys")
    result = {
        "job_id": _id(job["job_id"], "job_id"),
        "record_id": _id(job["record_id"], "record_id"),
        "kind": _id(job["kind"], "transform kind"),
        "parameters": job["parameters"],
        "seed": _uint(job["seed"], "job seed"),
        "sample_counter": _uint(job["sample_counter"], "job sample_counter"),
    }
    if type(result["parameters"]) is not dict:
        raise AugmentationError("job parameters must be a plain object")
    if result["kind"] not in _SCHEDULE_AUTHORITY["kinds"]:
        raise AugmentationError("unknown transform kind")
    if result["kind"] in _SCHEDULE_AUTHORITY["blocked_kinds"]:
        raise AugmentationError(f"requires_reannotation: {result['kind']} is not label-preserving")
    if result["parameters"] != {}:
        raise AugmentationError("unknown transform parameter")
    return result


class TrustedSchedule:
    __slots__ = ("_body_json", "_jobs", "_sources", "_cluster", "_split", "_sha256")

    def __init__(
        self,
        body: dict[str, Any],
        jobs: tuple[dict[str, Any], ...],
        sources: tuple[dict[str, Any], ...],
        cluster: ClusterAuthority,
        split: SplitAuthority,
        token: object,
    ) -> None:
        if token is not _SCHEDULE_TOKEN:
            raise TypeError("TrustedSchedule is produced by make_trusted_schedule")
        self._body_json = canonical_json(body)
        self._jobs = jobs
        self._sources = sources
        self._cluster = cluster
        self._split = split
        self._sha256 = digest(body)

    @property
    def schedule_sha256(self) -> str:
        return self._sha256

    @property
    def cluster_authority(self) -> ClusterAuthority:
        return self._cluster

    @property
    def split_authority(self) -> SplitAuthority:
        return self._split

    def schedule(self) -> dict[str, Any]:
        return copy.deepcopy(json.loads(self._body_json))

    def job(self, job_id: str) -> dict[str, Any]:
        for job in self._jobs:
            if job["job_id"] == job_id:
                return copy.deepcopy(job)
        raise AugmentationError(f"job is absent from trusted schedule: {job_id}")


_SCHEDULE_TOKEN = object()


def make_trusted_schedule(
    bundles: list[SourceBundle],
    jobs: list[Mapping[str, Any]],
    *,
    cluster_authority: ClusterAuthority,
    split_authority: SplitAuthority,
) -> TrustedSchedule:
    """Create an immutable assignment from source IDs and M3 authorities."""

    checked = _bundle_list(bundles)
    if type(cluster_authority) is not ClusterAuthority or type(split_authority) is not SplitAuthority:
        raise AugmentationError("trusted M3 cluster and split authorities are required")
    if split_authority.cluster is not cluster_authority:
        raise AugmentationError("split authority is not bound to the supplied cluster authority")
    if tuple(sorted(bundle.record["record_id"] for bundle in checked)) != split_authority.record_ids:
        raise AugmentationError("source bundle IDs do not equal the trusted split source set")
    for bundle in checked:
        record = bundle.record
        if _effective_split(record, split_authority) == "locked_test":
            raise AugmentationError("locked_test source is not augmentation-eligible")
        for asset_id in bundle.asset_ids:
            if cluster_authority.asset_sha256(asset_id) != bundle._decoded(asset_id).encoded_sha256:
                raise AugmentationError(f"source bytes disagree with M3 authority: {asset_id}")
    if type(jobs) is not list or not jobs:
        raise AugmentationError("trusted schedule jobs must be a non-empty list")
    parsed_jobs = tuple(_validate_job(job) for job in jobs)
    ids = [job["job_id"] for job in parsed_jobs]
    if ids != sorted(ids) or len(set(ids)) != len(ids):
        raise AugmentationError("schedule jobs must be uniquely canonical-ordered")
    counters = [(job["seed"], job["sample_counter"]) for job in parsed_jobs]
    if len(set(counters)) != len(counters):
        raise AugmentationError("schedule seed/sample counter collision")
    source_by_id = {bundle.record["record_id"]: bundle for bundle in checked}
    for job in parsed_jobs:
        if job["record_id"] not in source_by_id:
            raise AugmentationError("schedule job references an unknown source record")
    source_rows: list[dict[str, Any]] = []
    for bundle in sorted(checked, key=lambda value: value.record["record_id"]):
        record = bundle.record
        source_rows.append(
            {
                "record_id": record["record_id"],
                "record_sha256": digest(record),
                "split_owner": _effective_split(record, split_authority),
                "asset_ids": list(bundle.asset_ids),
                "asset_content_sha256": {asset_id: bundle._decoded(asset_id).encoded_sha256 for asset_id in bundle.asset_ids},
                "protected_families": _protected_families(record, cluster_authority),
            }
        )
    family_splits: dict[tuple[str, str], str] = {}
    for source in source_rows:
        split = source["split_owner"]
        for category in PROTECTED_CATEGORIES:
            for value in source["protected_families"][category]:
                key = (category, value)
                previous = family_splits.setdefault(key, split)
                if previous != split:
                    raise AugmentationError(f"protected {category} crosses split owners")
    config_sha256 = _current_config_sha256()
    body = {
        "schema_id": SCHEDULE_SCHEMA_ID,
        "schema_version": SCHEDULE_SCHEMA_VERSION,
        "config_sha256": config_sha256,
        "schedule_authority_sha256": _schedule_authority_sha256(),
        "cluster_receipt_sha256": cluster_authority.receipt_sha256,
        "split_manifest_sha256": split_authority.manifest_sha256,
        "source_count": len(source_rows),
        "sources": source_rows,
        "jobs": [dict(job) for job in parsed_jobs],
    }
    return TrustedSchedule(
        body,
        parsed_jobs,
        tuple(source_rows),
        cluster_authority,
        split_authority,
        _SCHEDULE_TOKEN,
    )


def _current_config_sha256() -> str:
    return digest(_config())


def _assert_authorities(
    schedule: TrustedSchedule,
    cluster_authority: ClusterAuthority,
    split_authority: SplitAuthority,
) -> None:
    if type(schedule) is not TrustedSchedule:
        raise AugmentationError("trusted schedule is required")
    if cluster_authority is not schedule.cluster_authority or split_authority is not schedule.split_authority:
        raise AugmentationError("validation authorities are not the schedule's trusted authorities")
    body = schedule.schedule()
    if body["config_sha256"] != _current_config_sha256():
        raise AugmentationError("frozen augmentation authority changed")
    if body["schedule_authority_sha256"] != _schedule_authority_sha256():
        raise AugmentationError("schedule authority digest changed")
    if body["cluster_receipt_sha256"] != cluster_authority.receipt_sha256:
        raise AugmentationError("cluster authority digest mismatch")
    if body["split_manifest_sha256"] != split_authority.manifest_sha256:
        raise AugmentationError("split authority digest mismatch")


def _source_row(schedule: TrustedSchedule, record_id: str) -> dict[str, Any]:
    for row in schedule._sources:
        if row["record_id"] == record_id:
            return row
    raise AugmentationError(f"source record is absent from trusted schedule: {record_id}")


def _check_bundle(
    bundle: SourceBundle,
    schedule: TrustedSchedule,
    cluster_authority: ClusterAuthority,
    split_authority: SplitAuthority,
    record_id: str,
) -> dict[str, Any]:
    if type(bundle) is not SourceBundle:
        raise AugmentationError("a canonical source bundle is required")
    record = _record(bundle.record)
    if record["record_id"] != record_id:
        raise AugmentationError("job record_id does not match source bundle")
    row = _source_row(schedule, record_id)
    if digest(record) != row["record_sha256"]:
        raise AugmentationError("source record changed after schedule assignment")
    if tuple(sorted(_required_asset_ids(record))) != tuple(row["asset_ids"]):
        raise AugmentationError("source asset set changed after schedule assignment")
    if _effective_split(record, split_authority) != split_authority.split(record_id):
        raise AugmentationError("source split owner changed after schedule assignment")
    for asset_id in bundle.asset_ids:
        actual = bundle._decoded(asset_id).encoded_sha256
        if actual != row["asset_content_sha256"][asset_id] or actual != cluster_authority.asset_sha256(asset_id):
            raise AugmentationError(f"source asset bytes changed after schedule assignment: {asset_id}")
    return record


def _flip_action(value: Any, label: str) -> Any:
    if value is None:
        return None
    if type(value) is not str:
        raise AugmentationError(f"invalid label ID at {label}")
    for left, right in ACTION_PAIRS:
        if value == left:
            return right
        if value == right:
            return left
    return value


def _flip_verifier(value: Any, label: str) -> Any:
    if type(value) is not str:
        raise AugmentationError(f"invalid verifier ID at {label}")
    for left, right in VERIFIER_PAIRS:
        if value == left:
            return right
        if value == right:
            return left
    return value


def _flip_action_list(values: Any, label: str) -> list[str]:
    if type(values) is not list:
        raise AugmentationError(f"invalid action list at {label}")
    return [_flip_action(value, f"{label}[{index}]") for index, value in enumerate(values)]


def _flip_region(region: Any, label: str) -> list[float | int]:
    if type(region) is not list or len(region) != 4:
        raise AugmentationError(f"invalid region at {label}")
    x, y, width, height = (_finite(value, f"{label}[{index}]") for index, value in enumerate(region))
    if not all(0.0 <= value <= 1.0 for value in (x, y, width, height)) or x + width > 1.0 or y + height > 1.0:
        raise AugmentationError(f"region is outside normalized frame at {label}")
    mirrored_x = 1.0 - x - width
    if 1.0 - mirrored_x - width != x:
        raise AugmentationError("requires_reannotation: geometry is not an exact involution")
    result: list[float | int] = [mirrored_x, y, width, height]
    # Preserve the exact input scalar types/values where a component is not
    # transformed; never round a full-precision coordinate.
    return result


def _flip_subject(subject: Mapping[str, Any]) -> dict[str, Any]:
    result = copy.deepcopy(dict(subject))
    candidates = result.get("candidates")
    if type(candidates) is not list:
        raise AugmentationError("subject candidates are not explicit")
    for index, candidate in enumerate(candidates):
        if type(candidate) is not dict:
            raise AugmentationError("subject candidate is not an object")
        if "region" in candidate:
            candidate["region"] = _flip_region(candidate["region"], f"subject.candidates[{index}].region")
    return result


def _flip_label(label: Mapping[str, Any]) -> dict[str, Any]:
    result = copy.deepcopy(dict(label))
    result["acceptable_action_ids"] = _flip_action_list(result["acceptable_action_ids"], "label.acceptable_action_ids")
    result["forbidden_action_ids"] = _flip_action_list(result["forbidden_action_ids"], "label.forbidden_action_ids")
    result["selected_action_id"] = _flip_action(result["selected_action_id"], "label.selected_action_id")
    for issue_index, issue in enumerate(result["issues"]):
        issue["acceptable_action_ids"] = _flip_action_list(issue["acceptable_action_ids"], f"label.issues[{issue_index}].acceptable_action_ids")
        issue["forbidden_action_ids"] = _flip_action_list(issue["forbidden_action_ids"], f"label.issues[{issue_index}].forbidden_action_ids")
    for index, verification in enumerate(result["verification"]):
        verification["action_id"] = _flip_action(verification["action_id"], f"label.verification[{index}].action_id")
        verification["verifier_id"] = _flip_verifier(verification["verifier_id"], f"label.verification[{index}].verifier_id")
    return result


def _targets(record: Mapping[str, Any], kind: str) -> dict[str, Any]:
    result: dict[str, Any] = {
        "capture": copy.deepcopy(record["capture"]),
        "subject": _flip_subject(record["subject"]) if kind == "horizontal_flip" else copy.deepcopy(record["subject"]),
        "label": _flip_label(record["label"]) if kind == "horizontal_flip" else copy.deepcopy(record["label"]),
    }
    if "sequence" in record:
        result["sequence"] = copy.deepcopy(record["sequence"])
    if "episode" in record:
        result["episode"] = copy.deepcopy(record["episode"])
        if kind == "horizontal_flip":
            result["episode"]["action_step"]["action_id"] = _flip_action(result["episode"]["action_step"]["action_id"], "episode.action_step.action_id")
            result["episode"]["outcome_verifier"] = _flip_verifier(result["episode"]["outcome_verifier"], "episode.outcome_verifier")
    return result


def _flip_pixels(asset: _DecodedAsset) -> bytes:
    row_size = asset.width * 3
    return b"".join(b"".join(asset.pixels[row * row_size + column * 3 : row * row_size + (column + 1) * 3] for column in range(asset.width - 1, -1, -1)) for row in range(asset.height))


def _result_pixels(bundle: SourceBundle, kind: str) -> dict[str, list[list[list[int]]]]:
    result: dict[str, list[list[list[int]]]] = {}
    for asset_id in bundle.asset_ids:
        asset = bundle._decoded(asset_id)
        packed = _flip_pixels(asset) if kind == "horizontal_flip" else asset.pixels
        result[asset_id] = _bytes_to_pixels(asset.height, asset.width, packed)
    return result


def _pixel_map_digest(pixels_by_asset: Mapping[str, Any], expected: Sequence[_DecodedAsset], kind: str) -> str:
    packed_assets: list[_DecodedAsset] = []
    for asset in expected:
        height, width, packed = _pixels_to_bytes(pixels_by_asset[asset.asset_id], f"pixels_by_asset.{asset.asset_id}")
        if (height, width) != (asset.height, asset.width):
            raise AugmentationError("output pixel shape changed")
        packed_assets.append(_DecodedAsset(asset.asset_id, b"", "", height, width, packed))
    return _asset_pixels_digest(packed_assets)


def _lineage(
    bundle: SourceBundle,
    record: Mapping[str, Any],
    job: Mapping[str, Any],
    schedule: TrustedSchedule,
    targets: Mapping[str, Any],
    pixels_by_asset: Mapping[str, Any],
) -> dict[str, Any]:
    expected_assets = tuple(bundle._decoded(asset_id) for asset_id in bundle.asset_ids)
    input_pixel_hash = _asset_pixels_digest(expected_assets)
    output_pixel_hash = _pixel_map_digest(pixels_by_asset, expected_assets, job["kind"])
    source_targets = _targets(record, "identity")
    body = {
        "schema_id": LINEAGE_SCHEMA_ID,
        "schema_version": AUGMENTATION_VERSION,
        "job_id": job["job_id"],
        "record_id": record["record_id"],
        "source_record_sha256": digest(record),
        "source_asset_content_sha256": {asset.asset_id: asset.encoded_sha256 for asset in expected_assets},
        "input_pixels_sha256": input_pixel_hash,
        "output_pixels_sha256": output_pixel_hash,
        "source_targets_sha256": digest(source_targets),
        "output_targets_sha256": digest(targets),
        "transform": {
            "kind": job["kind"],
            "version": AUGMENTATION_VERSION,
            "parameters": copy.deepcopy(job["parameters"]),
        },
        "seed": job["seed"],
        "sample_counter": job["sample_counter"],
        "config_sha256": _current_config_sha256(),
        "schedule_sha256": schedule.schedule_sha256,
        "cluster_receipt_sha256": schedule.cluster_authority.receipt_sha256,
        "split_manifest_sha256": schedule.split_authority.manifest_sha256,
        "protected_families": _source_row(schedule, record["record_id"])["protected_families"],
        "split_owner": _source_row(schedule, record["record_id"])["split_owner"],
    }
    return {**body, "receipt_sha256": digest(body)}


def _expected_result(bundle: SourceBundle, schedule: TrustedSchedule, job_id: str) -> dict[str, Any]:
    job = schedule.job(job_id)
    _assert_authorities(schedule, schedule.cluster_authority, schedule.split_authority)
    record = _check_bundle(bundle, schedule, schedule.cluster_authority, schedule.split_authority, job["record_id"])
    targets = _targets(record, job["kind"])
    pixels = _result_pixels(bundle, job["kind"])
    return {
        "job_id": job["job_id"],
        "record_id": record["record_id"],
        "pixels_by_asset": pixels,
        "targets": targets,
        "lineage": _lineage(bundle, record, job, schedule, targets, pixels),
    }


def augment(bundle: SourceBundle, schedule: TrustedSchedule, job_id: str) -> dict[str, Any]:
    """Replay one trusted assignment over every concrete asset in the bundle."""

    if type(schedule) is not TrustedSchedule or type(job_id) is not str:
        raise AugmentationError("augment requires a trusted schedule and job ID")
    expected = _expected_result(bundle, schedule, job_id)
    # Return independent mutable output; the immutable source bundle remains
    # the only source of canonical record/pixel truth.
    return copy.deepcopy(expected)


_RESULT_KEYS = {"job_id", "record_id", "pixels_by_asset", "targets", "lineage"}


def validate_result(
    bundle: SourceBundle,
    result: Mapping[str, Any],
    *,
    schedule: TrustedSchedule,
    cluster_authority: ClusterAuthority,
    split_authority: SplitAuthority,
) -> None:
    """Recompute pixels, targets, assignment, authority, and receipt."""

    _assert_authorities(schedule, cluster_authority, split_authority)
    if type(result) is not dict or set(result) != _RESULT_KEYS:
        raise AugmentationError("result has unknown or missing keys")
    expected = _expected_result(bundle, schedule, result["job_id"])
    try:
        actual_json = canonical_json(dict(result))
        expected_json = canonical_json(expected)
    except AugmentationError:
        raise
    if actual_json != expected_json:
        raise AugmentationError("result does not replay from the trusted source bundle and schedule")


def validate_lineage_batch(
    bundles: list[SourceBundle],
    results: list[Mapping[str, Any]],
    *,
    schedule: TrustedSchedule,
    cluster_authority: ClusterAuthority,
    split_authority: SplitAuthority,
) -> None:
    """Admit a complete scheduled batch after rerunning M3 over every asset."""

    _assert_authorities(schedule, cluster_authority, split_authority)
    if type(bundles) is not list or type(results) is not list or not bundles or not results:
        raise AugmentationError("lineage batch must be a non-empty list of complete jobs")
    bundle_by_id = {bundle.record["record_id"]: bundle for bundle in _bundle_list(bundles)}
    expected_records = {row["record_id"] for row in schedule._sources}
    if set(bundle_by_id) != expected_records:
        raise AugmentationError("batch source bundle set is incomplete or has extras")
    result_ids = []
    for result in results:
        if type(result) is not dict or type(result.get("job_id")) is not str:
            raise AugmentationError("batch result has no valid job ID")
        result_ids.append(result["job_id"])
    expected_jobs = {job["job_id"] for job in schedule._jobs}
    if set(result_ids) != expected_jobs or len(result_ids) != len(expected_jobs):
        raise AugmentationError("batch result set is incomplete, duplicated, or has extras")
    # This is an independent replay of the M3-008 authorities across every
    # supplied asset, not trust in receipt hashes copied by a caller.
    rebuilt_cluster = make_cluster_authority(bundles)
    if rebuilt_cluster.receipt_sha256 != cluster_authority.receipt_sha256:
        raise AugmentationError("batch assets do not reproduce trusted M3 cluster authority")
    rebuilt_split = make_split_authority(
        bundles,
        cluster_authority,
        seed=split_authority.seed,
        train_ratio=split_authority.ratios["train"],
        calibration_ratio=split_authority.ratios["calibration"],
        locked_test_ratio=split_authority.ratios["locked_test"],
    )
    if rebuilt_split.manifest_sha256 != split_authority.manifest_sha256:
        raise AugmentationError("batch sources do not reproduce trusted M3 split authority")
    for result in results:
        job = schedule.job(result["job_id"])
        validate_result(
            bundle_by_id[job["record_id"]],
            result,
            schedule=schedule,
            cluster_authority=cluster_authority,
            split_authority=split_authority,
        )
    families: dict[tuple[str, str], str] = {}
    for source in schedule._sources:
        for category in PROTECTED_CATEGORIES:
            for value in source["protected_families"][category]:
                key = (category, value)
                owner = families.setdefault(key, source["split_owner"])
                if owner != source["split_owner"]:
                    raise AugmentationError(f"protected {category} crosses split owners")


def _manifest_pairs(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise AugmentationError("derivation manifest has duplicate JSON keys")
        result[key] = value
    return result


_MANIFEST_KEYS = frozenset(
    {
        "manifest_type",
        "schema_id",
        "manifest_version",
        "manifest_id",
        "manifest_sha256",
        "entry_schema",
        "record_count",
        "hash_algorithm",
        "raw_data_location",
        "rights_uncleared_location",
        "template_only",
        "independence_rule",
        "augmentation_policy_schema_id",
        "augmentation_lineage_schema_id",
        "augmentation_config_sha256",
        "schedule_schema_id",
        "schedule_authority_sha256",
    }
)


def validate_derivation_manifest(path: Path | str = DERIVATION_MANIFEST_PATH) -> dict[str, Any]:
    manifest_path = Path(path)
    try:
        lines = manifest_path.read_text(encoding="utf-8").splitlines()
        if len(lines) != 1 or not lines[0]:
            raise AugmentationError("derivation manifest must contain one JSONL header")
        payload = json.loads(lines[0], object_pairs_hook=_manifest_pairs)
    except (OSError, json.JSONDecodeError) as exc:
        raise AugmentationError(f"invalid derivation manifest: {manifest_path}") from exc
    if type(payload) is not dict or set(payload) != _MANIFEST_KEYS:
        raise AugmentationError("derivation manifest has unknown or missing keys")
    if canonical_json(payload) != lines[0]:
        raise AugmentationError("derivation manifest is not canonical JSON")
    if payload["manifest_type"] != "derivation" or payload["schema_id"] != "camera-derivation-manifest-v1":
        raise AugmentationError("derivation manifest schema mismatch")
    if payload["manifest_version"] != RECORD_SCHEMA_VERSION or payload["entry_schema"] != "camera-derivation-entry-v1":
        raise AugmentationError("derivation manifest version mismatch")
    if payload["manifest_id"] != "camera-derivation-manifest" or payload["hash_algorithm"] != "sha256":
        raise AugmentationError("derivation manifest identity mismatch")
    if type(payload["record_count"]) is not int or isinstance(payload["record_count"], bool) or payload["record_count"] != 0:
        raise AugmentationError("derivation manifest must remain zero-record")
    if payload["raw_data_location"] != "outside_git" or payload["rights_uncleared_location"] != "outside_git" or payload["template_only"] is not True:
        raise AugmentationError("derivation manifest storage/template policy mismatch")
    if payload["augmentation_policy_schema_id"] != POLICY_SCHEMA_ID or payload["augmentation_lineage_schema_id"] != LINEAGE_SCHEMA_ID:
        raise AugmentationError("derivation manifest augmentation binding mismatch")
    if payload["schedule_schema_id"] != SCHEDULE_SCHEMA_ID or payload["schedule_authority_sha256"] != _schedule_authority_sha256():
        raise AugmentationError("derivation manifest schedule binding mismatch")
    if payload["augmentation_config_sha256"] != _current_config_sha256():
        raise AugmentationError("derivation manifest configuration binding mismatch")
    if payload["independence_rule"] != "only explicitly independent source decisions count toward a split quota":
        raise AugmentationError("derivation manifest independence rule mismatch")
    expected = digest({key: value for key, value in payload.items() if key != "manifest_sha256"})
    if payload["manifest_sha256"] != expected:
        raise AugmentationError("derivation manifest hash mismatch")
    return copy.deepcopy(payload)


__all__ = [
    "ACTION_PAIRS",
    "AUGMENTATION_CONFIG",
    "AUGMENTATION_CONFIG_SHA256",
    "AugmentationError",
    "ClusterAuthority",
    "DERIVATION_MANIFEST_PATH",
    "LINEAGE_SCHEMA_ID",
    "POLICY_SCHEMA_ID",
    "REMAP_AUTHORITY_SHA256",
    "SCHEDULE_AUTHORITY_SHA256",
    "SCHEDULE_SCHEMA_ID",
    "SourceBundle",
    "SplitAuthority",
    "TrustedSchedule",
    "VERIFIER_PAIRS",
    "augment",
    "canonical_json",
    "digest",
    "make_cluster_authority",
    "make_source_bundle",
    "make_split_authority",
    "make_trusted_schedule",
    "validate_derivation_manifest",
    "validate_lineage_batch",
    "validate_result",
]
