"""Disabled camera-coach model candidates; no runtime provider is enabled."""

from .set_composition_net import (
    CandidateA,
    CandidateB,
    ContractError,
    SETCompositionNetCandidateA,
    SETCompositionNetCandidateB,
    SETCompositionNetInputs,
    SETCompositionNetManifest,
    count_macs,
    count_parameters,
)
from .set_composition_net_v2 import (
    CandidateAv2,
    CandidateBv2,
    INTENT_CONDITIONED_HEAD_ORDER,
    INTENT_ORDER,
    INTENT_STYLE_NAMES,
    KNOWN_FLAG_INDEX,
    SETCompositionNetV2CandidateA,
    SETCompositionNetV2CandidateB,
    SETCompositionNetV2Inputs,
    SETCompositionNetV2Manifest,
    encode_intent,
    intent_supervision_mask,
    validate_intent_features,
)

__all__ = [
    "CandidateA",
    "CandidateAv2",
    "CandidateB",
    "CandidateBv2",
    "ContractError",
    "INTENT_CONDITIONED_HEAD_ORDER",
    "INTENT_ORDER",
    "INTENT_STYLE_NAMES",
    "KNOWN_FLAG_INDEX",
    "SETCompositionNetCandidateA",
    "SETCompositionNetCandidateB",
    "SETCompositionNetInputs",
    "SETCompositionNetManifest",
    "SETCompositionNetV2CandidateA",
    "SETCompositionNetV2CandidateB",
    "SETCompositionNetV2Inputs",
    "SETCompositionNetV2Manifest",
    "count_macs",
    "count_parameters",
    "encode_intent",
    "intent_supervision_mask",
    "validate_intent_features",
]
